name: pass_mgr
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  hive: ^2.2.3
  dio: ^5.5.0+1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.0.11 # Add path_provider for file operations

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/logo.jpg"

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/